### ISSUE TITLE
The question about spectral image projected on rgb image

### ISSUE THREAD

**Issue by wuyujiji** [icvl/shred#2]
Excuse me! The shredProjectImage.m file is making spectral image projected on rgb? I use this function and get a rgb image which is much differences with original rgb image.

**Comment by boazarad** [comment]
The result of shredProjectImage depends on the response function used. Note
that RGB images on display at the ICVL database website are color corrected
for display purposes. Applying white balance to the result of
shredProjectImage should produce a similar result with most RGB camera
response functions.

**Comment by wuyujiji** [comment]
thanks for your reply

**Comment by ImYannChan** [comment]
> Excuse me! The shredProjectImage.m file is making spectral image projected on rgb? I use this function and get a rgb image which is much differences with original rgb image.

同学你好，我怎么才能联系你，我最近也在复现这篇论文
