### ISSUE TITLE
File download

### ISSUE THREAD

**Issue by Heli99** [icvl/shred#3]
Excuse me! The link to download the file ‘sample_hs_im.mat’ has expired.Could you please update the link?

**Comment by boazV81** [comment]
The link appears to work on my end, could you please provide additional details about the error  you’re seeing?

**Comment by Heli99** [comment]
> The link appears to work on my end, could you please provide additional details about the error  you’re seeing?
In the README.md :
sample_hs_im.mat can be downloaded **here** alternatively, you can use any image from the BGU ICVL Natural Hyperspectral Image
When I click the link corresponding to "here", display that unable to access this page.

**Comment by Heli99** [comment]
Sorry to disturb you, I just touched on the content of image reflectance reconstruction. I don’t know where and how to start. If convenient, can you please provide some basic tutorials/codes of reflectance reconstruction based on MATLAB?

**Comment by boazV81** [comment]
Could you please post a screenshot of the error you’re receiving when clicking the link?

As for reflectance recovery, I suggest reading the papers found here:
http://icvl.cs.bgu.ac.il/hyperspectral-imaging/ 

As well as the “NTIRE 2018 Challenge on Spectral Reconstruction from RGB Images” review paper.

**Comment by Heli99** [comment]
Thank you for your reply.
After I chick:
![1576651383](https://user-images.githubusercontent.com/58944738/71062353-3a521600-21a5-11ea-912f-80877e9bbbc7.png)
I guess it may be the country's restrictions on access to some websites, and now some websites are not available in China.

**Comment by Heli99** [comment]
So could you please send it to me by email?My email address is:2018202320@tju.edu.cn. Thank you very much.

**Comment by Heli99** [comment]
Should I be able to use other ".mat" files in the BGU iCVL HS Database? The link corresponding to the database worked for me.

**Comment by boazV81** [comment]
Yes, any of the .MAT files there should work.
